---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): github-actions"
      include: "scope"
    labels:
      - "github-actions"
      - "dependencies"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): docker"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
  - package-ecosystem: poetry
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps): pip"
      include: "scope"
    labels:
      - "pip"
      - "dependencies"
