---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: redis-config
    envs:
      - redis-config.env

commonLabels:
  app.kubernetes.io/instance: redis
  app.kubernetes.io/name: redis
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: runner-manager
images:
  - name: redis
    newName: redis/redis-stack
    newTag: 6.2.6-v9
resources:
  - statefulset.yaml
  - service.yaml
